x = 10
def funcao():
    y = 5
    print(x*y)
funcao()
#print(y) retorna erro pois Ã© uma var interna da "funcao"
print(x)

